# -*- coding: utf-8 -*-
"""train_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FM6icR24CM1TOeLuaqjK23BLVu83A8e1
"""

# 1. IMPORTS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

# Machine Learning Libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Algorithms
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

data = pd.read_csv('patient_data.csv')

data.rename(columns={'C':"Gender"}, inplace=True)

data['TakeMedication'] = data['TakeMedication'].replace({'Yes ': 'Yes'})
data['NoseBleeding'] = data['NoseBleeding'].replace({'No ': 'No'})
# Standardizing Ranges
data['Systolic'] = data['Systolic'].replace({'121- 130': '121 - 130', '100+': '100 - 110'})
data['Diastolic'] = data['Diastolic'].replace({'130+': '100+'})
# Fixing Target Variable Typos
data['Stages'] = data['Stages'].replace({
    'HYPERTENSION (Stage-2).': 'HYPERTENSION (Stage-2)',
    'HYPERTENSIVE CRISI': 'HYPERTENSIVE CRISIS'
})

initial_count = len(data)
data.drop_duplicates(inplace=True)
print(f"Duplicates Removed: {initial_count - len(data)}")
print(f"Final Dataset Size: {len(data)}")

plt.figure(figsize=(6,4))
sns.countplot(data=data, x="Gender", palette="Set2")
plt.title("Gender Distribution")
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(data=data, x="Stages", palette="coolwarm")
plt.title("Hypertension Stages Distribution")
plt.xticks(rotation=30)
plt.show()

def range_to_midpoint(val):
    if "-" in val:
        start, end = val.split("-")
        return (int(start.strip()) + int(end.strip()))/2
    elif "+" in val:
        return int(val.replace("+","").strip())
    return np.nan

data['Systolic_num'] = data['Systolic'].apply(range_to_midpoint)
data['Diastolic_num'] = data['Diastolic'].apply(range_to_midpoint)

plt.figure(figsize=(6,5))
sns.heatmap(data[['Systolic_num', 'Diastolic_num']].corr(), annot=True, cmap="Blues")
plt.title("Correlation: Systolic vs Diastolic")
plt.show()

data.drop(columns=['Systolic_num', 'Diastolic_num'], inplace=True)

binary_map = {'No': 0, 'Yes': 1}
binary_cols = ['History', 'Patient', 'TakeMedication', 'BreathShortness',
               'VisualChanges', 'NoseBleeding', 'ControlledDiet']

for col in binary_cols:
    data[col] = data[col].map(binary_map)

# Gender Encoding
data['Gender'] = data['Gender'].map({'Male': 0, 'Female': 1})

# Ordinal Encoding (Categories with order)
data['Age'] = data['Age'].map({'18-34': 1, '35-50': 2, '51-64': 3, '65+': 4})
data['Severity'] = data['Severity'].map({'Mild': 0, 'Moderate': 1, 'Sever': 2, 'Severe': 2})
data['Whendiagnoused'] = data['Whendiagnoused'].map({'<1 Year': 1, '1 - 5 Years': 2, '>5 Years': 3})
data['Systolic'] = data['Systolic'].map({'100 - 110': 0, '111 - 120': 1, '121 - 130': 2, '130+': 3})
data['Diastolic'] = data['Diastolic'].map({'70 - 80': 0, '81 - 90': 1, '91 - 100': 2, '100+': 3})

data['Stages'] = data['Stages'].map({
    'NORMAL': 0,
    'HYPERTENSION (Stage-1)': 1,
    'HYPERTENSION (Stage-2)': 2,
    'HYPERTENSIVE CRISIS': 3
})

ordinal_features = ['Age', 'Severity', 'Whendiagnoused', 'Systolic', 'Diastolic']
scaler = MinMaxScaler()
data[ordinal_features] = scaler.fit_transform(data[ordinal_features])

X = data.drop("Stages", axis=1)
y = data['Stages']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Training Set: {X_train.shape[0]} samples")
print(f"Testing Set: {X_test.shape[0]} samples")

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "SVM": SVC(random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Naive Bayes": GaussianNB(),
    "Ridge Classifier": RidgeClassifier(random_state=42)
}

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    results[name] = acc
    print(f"{name} Accuracy: {acc*100:.2f}%")

print("\n--- Final Model Selection ---")
selected_model = models["Logistic Regression"]
print("Selected Model: Logistic Regression")

with open('logreg_model.pkl', 'wb') as f:
    pickle.dump(selected_model, f)

with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

print("SUCCESS: 'logreg_model.pkl' and 'scaler.pkl' saved.")

